name: geno
channels:
  - conda-forge
dependencies:
  - conda-forge::ipykernel=5.1.3
  - conda-forge::ipywidgets=7.5.1
  - conda-forge::matplotlib=3.1.2
  - conda-forge::nb_conda_kernels=2.2.2
  - conda-forge::notebook=6.0.1
  - conda-forge::numpy=1.17.3
  - conda-forge::pandas=0.25.3
  - conda-forge::pip=19.3.1
  - conda-forge::python=3.7.3
  - conda-forge::requests=2.21.0
  - conda-forge::scikit-learn=0.20.3
  - conda-forge::scipy=1.2.1
  - conda-forge::seaborn=0.9.0
  - conda-forge::statsmodels=0.10.1
  - conda-forge::tqdm=4.31.1
  - conda-forge::xlrd=1.2.0
  - conda-forge::r-biocmanager=1.30.10
  - conda-forge::r-caret=6.0_84
  - conda-forge::r-gridextra=2.3
  - conda-forge::r-tidyverse=1.2.1
  - conda-forge::r-hexbin=1.28.0
  - conda-forge::r-irkernel=1.1
  - conda-forge::r-ggbeeswarm=0.6.0
  - conda-forge::r-ggextra=0.8
  - conda-forge::r-ggforce=0.2.2
  - conda-forge::r-ggrepel=0.8.1
  - conda-forge::r-mlmetrics=1.1.1
  - conda-forge::r-cowplot=1.0.0
  - conda-forge::r-rocr=1.0_7
  - conda-forge::r-proc=1.15.0
  - bioconda::bioconductor-biomart=2.42.0
  - pip:
    - hail==0.2.30


